// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl1XFJQ4eTZvPHUjP8v10jO0bfEUyRQpg',
    appId: '1:1007733381246:web:eed96a460722a59655202f',
    messagingSenderId: '1007733381246',
    projectId: 'fir-signin-27513',
    authDomain: 'fir-signin-27513.firebaseapp.com',
    storageBucket: 'fir-signin-27513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSWFMzHQwqsYa2dVLTxnku59VvHMb1C8',
    appId: '1:1007733381246:android:3a30f24b39339c4155202f',
    messagingSenderId: '1007733381246',
    projectId: 'fir-signin-27513',
    storageBucket: 'fir-signin-27513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPPAlnrriemMCJ3p8C3diElujDTf_Ft8',
    appId: '1:1007733381246:ios:2b1227ce18a0f19955202f',
    messagingSenderId: '1007733381246',
    projectId: 'fir-signin-27513',
    storageBucket: 'fir-signin-27513.appspot.com',
    iosClientId: '1007733381246-cc7a6uefvr5bi5ca2kor5purgcnu1ugm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOPPAlnrriemMCJ3p8C3diElujDTf_Ft8',
    appId: '1:1007733381246:ios:2b1227ce18a0f19955202f',
    messagingSenderId: '1007733381246',
    projectId: 'fir-signin-27513',
    storageBucket: 'fir-signin-27513.appspot.com',
    iosClientId: '1007733381246-cc7a6uefvr5bi5ca2kor5purgcnu1ugm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
